'use strict';

// Bundle src/ (plain CommonJS) into dist/index.js with a tiny module registry.
// No third-party bundler: every file becomes a function keyed by its path.

const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const entry = 'src/main.js';

function walk(dir) {
  return fs.readdirSync(path.join(root, dir), { withFileTypes: true }).flatMap((d) => {
    const rel = `${dir}/${d.name}`;
    if (d.isDirectory()) return walk(rel);
    return /\.(js|json)$/.test(d.name) ? [rel] : [];
  });
}

const files = walk('src').sort();
const modules = files.map((rel) => {
  const source = fs.readFileSync(path.join(root, rel), 'utf8').replace(/^#!.*\n/, '');
  const body = rel.endsWith('.json') ? `module.exports = ${JSON.stringify(JSON.parse(source))};` : source;
  return `${JSON.stringify(rel)}: function (module, exports, require) {\n${body}\n}`;
});

const runtime = `
const __path = require('path');
const __cache = {};
function __load(id) {
  if (__cache[id]) return __cache[id].exports;
  const module = { exports: {} };
  __cache[id] = module;
  __modules[id].call(module.exports, module, module.exports, (request) => {
    if (!request.startsWith('.')) return require(request);
    const base = __path.posix.join(__path.posix.dirname(id), request);
    const found = [base, base + '.js', base + '.json', base + '/index.js'].find((c) => __modules[c]);
    if (!found) throw new Error('Cannot find bundled module ' + request + ' from ' + id);
    return __load(found);
  });
  return module.exports;
}
__load(${JSON.stringify(entry)});
`;

const out = `'use strict';\n// Generated by scripts/build.js from src/. Do not edit by hand.\nconst __modules = {\n${modules.join(',\n')}\n};\n${runtime}`;
fs.mkdirSync(path.join(root, 'dist'), { recursive: true });
fs.writeFileSync(path.join(root, 'dist/index.js'), out);
console.log(`Bundled ${files.length} files into dist/index.js (${out.length} bytes).`);
